---
- hosts: all
  become: true
  vars:
    package_list:
      - httpd
      - php
      - php-mysqlnd
      - php-gd
      - php-xml
      - mariadb-server
      - mariadb
      - php-mbstring
      - php-json
      - wget
    service_list:
      - mariadb
      - httpd
  tasks:
    - name : Marking the correct php version 
      shell: sudo dnf module enable php:7.4 -y
    - name: install pacakges using dnf
      dnf:
        name: "{{ item }}"
        state: latest
      loop: "{{ package_list }}"
    - name: starting the service mariadb
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: starting the service httpd
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Update DNF Package repository cache
      dnf:
         update_cache: True
    - name: Install MySQL server on CentOS 8  
      dnf:
         name: mysql-server
         state: present
      ignore_errors: true
    - name: Install MySQL client on CentOS 8
      dnf:
         name: mysql
         state: present
      ignore_errors: true
    - name: Make sure mysqld service is running
      service:
         name: mysqld
         state: started
         enabled: True

    - name: Install python3-PyMySQL library
      dnf:
         name: python3-PyMySQL
         state: present
      ignore_errors: true
        

    - name: Set MySQL root Password
      mysql_user:
        login_host: 'localhost'
        login_user: 'root'
        login_password: ''
        name: 'root'
        password: ""
        state: present

    - name: create media wiki user in database
      mysql_user:
        name: wiki
        host: localhost
        password: 'password'
        priv: '*.*:ALL'
      tags:
        - mysql
    - name: create database
      mysql_db:
        name: wikidatabase
        state: present
      tags:
        - mysql
    - name: restarting the services
      service:
        name: "{{ item }}"
        state: restarted
      loop: "{{ service_list }}"
      tags:
        - mysql

    - name: Installing the mediawiki tar
      get_url:
        url: https://releases.wikimedia.org/mediawiki/1.36/mediawiki-1.36.0.tar.gz
        dest: /home/ec2-user/mediawiki-1.36.0.tar.gz
      tags:
        - app
    - name: Installing media wiki 
      shell: |
        cd /var/www
        tar -zxf /home/ec2-user/mediawiki-1.36.0.tar.gz
        ln -s mediawiki-1.36.0/ mediawiki
      tags:
        - app
    - name: Post steps after Installination for mediawiki
      shell: |
        cd /var/www
        ln -s mediawiki-1.36.0/ mediawiki
        chown -R apache:apache /var/www/mediawiki-1.36.0 
      tags:
        - conf
    - name: Putting the correct conf file
      copy:
        src: httpd.conf
        dest: /etc/httpd/conf
        force: yes
      tags:
        - conf
    - name: restarting the services
      service:
        name: httpd
        state: restarted
      tags:
        - restart
          